# Generated by Django 3.1.3 on 2021-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0002_auto_20210614_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovierequest',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
