# Generated by Django 3.1.3 on 2021-06-14 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0003_auto_20210614_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('lastupdated', models.DateTimeField(db_column='lastUpdated')),
                ('isdeleted', models.IntegerField(db_column='isDeleted')),
                ('mid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, to='popcorn.movie')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
