# Generated by Django 3.1.3 on 2021-06-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0005_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviegenre',
            fields=[
                ('mid', models.OneToOneField(db_column='mid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='popcorn.movie')),
            ],
            options={
                'db_table': 'moviegenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movierating',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('isdeleted', models.IntegerField(db_column='isDeleted')),
            ],
            options={
                'db_table': 'movierating',
                'managed': False,
            },
        ),
    ]
