# Generated by Django 3.1.3 on 2021-06-14 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0006_moviegenre_movierating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='Genre',
        ),
    ]
