# Generated by Django 3.1.3 on 2021-06-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0007_auto_20210614_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moviegenre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={},
        ),
    ]
