# Generated by Django 3.1.3 on 2021-06-14 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn', '0008_auto_20210614_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='gid',
            field=models.ForeignKey(db_column='gid', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='popcorn.genre'),
        ),
        migrations.AddField(
            model_name='movierating',
            name='mid',
            field=models.ForeignKey(db_column='mid', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='popcorn.movie'),
        ),
        migrations.AddField(
            model_name='movierating',
            name='uid',
            field=models.ForeignKey(db_column='uid', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
